### ISSUE TITLE
[Geral] Desenvolver layout inicial do aplicativo

### ISSUE THREAD

**Issue by JeanCHilger** [grintex/app-covid#1]
# Descrição
Desenvolver tela inicial (home) do aplicativo, de acordo com o *mockup* abaiaxo.

# *Mockup*
![image](https://user-images.githubusercontent.com/19687197/80512013-4c15a800-8953-11ea-87d0-5e60504fcc09.png)

# Assets
Conteúdos necessários para o desenvolvimento desta issue.
## Icones
Os ícones estão na ordem mostrada no *mockup*.
- [Estou com COVID-19?](https://www.flaticon.com/free-icon/question_2353678?term=man%20doubt&page=1&position=1)
- [Sobre a COVID-19](https://www.flaticon.com/free-icon/coronavirus_2750762)
- [Sintomas](https://www.flaticon.com/free-icon/cough_2328345?term=cough&page=1&position=7)
- [Grupos de risco](https://www.flaticon.com/free-icon/couple_437519)
- [Medidas de Prevençao](https://www.flaticon.com/free-icon/hand-wash_2707436?term=Coronavirus&page=1&position=34)
- [Onde Procurar Atendimento](https://www.flaticon.com/free-icon/hospital-building_946317)
- [Estatísticas](https://www.flaticon.com/free-icon/bar-chart_1270345)
- [Notícias](https://www.flaticon.com/free-icon/newspaper_1074055)
- [Telefones Úteis](https://www.flaticon.com/free-icon/medical-mask_2750740?term=mask&page=1&position=12)
- [Sobre o Aplicativo](https://www.flaticon.com/free-icon/information_1076337?term=info&page=1&position=37)

**Comment by Dovyski** [comment]
Estou trabalhando nessa tarefa, mas não no layout, apenas na criação das páginas e dos links que vão ligar todas elas.

**Comment by Dovyski** [comment]
Acabei de fazer o merge de 599a4527273c96dbc17e2694b7a1a93fc9ab6789 que adiciona todas as páginas do app. A página "Sobre a COVID-19", por exemplo, está em `pages/about-covid.f7.html`.

Continuarei trabalhando nessa tarefa para integrar o layout. Os links estão todos funcionando.

**Comment by mateusKoppe** [comment]
Feito!
