### ISSUE TITLE
Alterações no menu "Medidas de prevenção"

### ISSUE THREAD

**Issue by rafaelfagu** [grintex/app-covid#103]
Remover os vídeos e textos referentes aos vídeos (Eles serão movidos para outro menu - Descrição em outra issue) e acrescentar as seguintes imagens e textos.

Acrescentar texto:
Acrescentar imagem https://www.flaticon.com/free-icon/hand-wash_2707436?term=Coronavirus&page=1&position=34 seguida do texto:
Lave com frequência as mãos até a altura dos punhos ou então higienize com álcool em gel 70%. 

Acrescentar texto:
Ao tossir ou espirrar, cubra nariz e boca com lenço ou com o braço, e não com as mãos. 
Combinar as imagens e acrescentar no texto:
https://www.flaticon.com/free-icon/cough_2833227?term=breathing&page=2&position=21 
https://www.flaticon.com/free-icon/cancel_391247?term=close&page=1&position=53
  e  da seguinte forma: 
![img](https://user-images.githubusercontent.com/64489938/81183836-06299700-8f86-11ea-85c9-25b2dfaf13a5.png)

Alterar textos abaixo:
Evite tocar olhos, nariz e boca com as mãos não lavadas ou não higienizadas com álcool em gel 70%.
Se estiver doente, evite contato físico com outras pessoas, principalmente idosos e doentes crônicos e fique em casa até melhorar.

**Comment by Dovyski** [comment]
@rafaelfagu qual é a issue relacionada com os vídeos?

**Comment by Dovyski** [comment]
Essa issue está oficialmente concluída, falta saber onde colocar os vídeos que foram removidos. Para referência futura e agilidade, aqui está o código dos vídeos:

```html
                        <li>
                            <div class="item-content display-flex flex-direction-column-reverse">
                                <div class="item-media prevention-list__video">
                                    <iframe src="https://www.youtube.com/embed/krSDE0_KBMs" frameborder="0"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen class="w-inherit h-inherit"
                                    >
                                    </iframe>
                                </div>
                                <div class="item-inner no-margin">
                                    <div class="item-text">
                                        Lave com frequência as mãos até a altura dos punhos ou então
                                        higienize com álcool em gel 70%.
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="item-content display-flex flex-direction-column-reverse">
                                <div class="item-media prevention-list__video">
                                    <iframe src="https://www.youtube.com/embed/aEZY2n5wkks?list=PLGGHoUAM3Mh7bSnGFQL8JdcKJtGLSJ28D"
                                        frameborder="0" allowfullscreen class="w-inherit h-inherit"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    >
                                    </iframe>
                                </div>
                                <div class="item-inner no-margin">
                                    <div class="item-text">
                                        <strong>Pratique a etiqueta respiratória!</strong> Ao tossir ou
                                        espirrar, cubra nariz e boca com lenço ou com o braço, e não com
                                        as mãos.
                                    </div>
                                </div>
                            </div>
                        </li>
```

**Comment by brendathomas** [comment]
Os vídeos vão ser colocados no ícone "Dicas", que substitui o nome do antigo ícone "Como fazer sua máscara". Assim pensamos em colocas todos os vídeos lá.
