### ISSUE TITLE
 "ONDE PROCURAR ATENDIMENTO": alterações no item "OUTROS LOCAIS DE ATENDIMENTO EM CHAPECÓ" 

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#104]
Fazer as seguintes alterações no item "OUTROS LOCAIS DE ATENDIMENTO EM CHAPECÓ" dentro do ícone "ONDE PROCURAR ATENDIMENTO":

- Alterar texto: “Outros locais de atendimento em Chapecó” para “Atendimento emergencial em Chapecó”
- Dentro dessa opção os textos estão sem quebra de linha e não aparecem por completo. Sugestão é alterar o horário de atendimento para a linha seguinte.
- As opções de link do atendimento informam o telefone mas esse link para ligação não funciona, encaminhando apenas para o google maps (fazer link para ligação de telefone)

**Comment by JeanCHilger** [comment]
@brendathomas, deve haver links para o mapa e para ligação, ou apenas para ligação?

**Comment by brendathomas** [comment]
@JeanCHilger Para o mapa e para a ligação
