### ISSUE TITLE
 "COMO FAZER SUA MÁSCARA": alteração do ícone para "DICAS"

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#107]
- Alterar o ícone "COMO FAZER SUA MÁSCARA" para "DICAS"
- Colocar a seguinte imagem no ícone: https://www.flaticon.com/free-icon/chat_2227872?term=Tips&page=1&position=5

- Colocar as seguintes frases, imagens e vídeos:

-  Aprenda a lavar as mãos corretamente
    - Colocar imagem pequena ao lado da frase: https://www.flaticon.com/free-icon/hand-wash_2707436?term=Coronavirus&page=1&position=34
   - Incorporar vídeo: https://www.youtube.com/watch?time_continue=44&v=krSDE0_KBMs&feature=emb_title

- Como fazer sua máscara
   - Colocar imagem pequena ao lado da frase: https://www.flaticon.com/free-icon/medical-mask_2750740?term=mask&page=1&position=12
   - Incorporar vídeo: https://www.youtube.com/watch?v=VNYEgEWrJKw&list=PL_rQTI99G4P92OkQCzsXoYpS8oBj7GOu6&index=11

- 10 passos para evitar a propagação do coronavírus
   - Colocar imagem pequena ao lado da frase: https://www.flaticon.com/free-icon/physical_2885288?term=keep%20distance&page=1&position=7
    - Incorporar vídeo: https://www.facebook.com/watch/?v=232176374773455

- Pratique a etiqueta respiratória! Ao tossir ou espirrar, cubra nariz e boca com lenço ou com o braço, e não com as mãos
    - Colocar imagem pequena ao lado da frase (OBS: Combinar as imagens, o X pequeno no canto inferior esquerdo da imagem do homem espirrando na mão) 
    https://www.flaticon.com/free-icon/cough_2833227?term=breathing&page=2&position=21 
    https://www.flaticon.com/free-icon/cancel_391247?term=close&page=1&position=53
    - Incorporar vídeo: https://youtu.be/aEZY2n5wkks?list=PLGGHoUAM3Mh7bSnGFQL8JdcKJtGLSJ28D

**Comment by rafaelfagu** [comment]
Essa é a isssue de alteração dos vídeos professor @Dovyski .

**Comment by Dovyski** [comment]
Fixed by https://github.com/grintex/app-covid/pull/160.
