### ISSUE TITLE
"SOBRE O APP": texto cortado

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#137]
No ícone "SOBRE O APP" o texto que está na parte de cima está cortado. Não sei exatamente o que o texto diz na íntegra, mas acredito que pode ser retirado, visto que pelo menos o início contêm as informações que estão descritas logo abaixo em "Sobre o projeto"

**Comment by brendathomas** [comment]
@Dovyski Essa issue ainda não foi resolvida, não sei como colocar na milestonse v1.1.0

**Comment by Dovyski** [comment]
Fixed by https://github.com/grintex/app-covid/pull/160.
