### ISSUE TITLE
"ONDE PROCURAR ATENDIMENTO": mudanças no item "Atendimento emergencial em Chapecó"

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#141]
Dentro do ícone "ONDE PROCURAR ATENDIMENTO", fazer as seguintes mudanças no item "Atendimento emergencial em Chapecó":

- Tirar o endereço que consta no "Ambulatório de Campanha"
- Colocar dois subtópicos, 2 Ambulatórios de Campanha, no caso:

     - Centro
          Ginásio de Esportes Ivo Silveira
          Horário: 7h às 19h

   - Efapi
          Ao lado do Pronto Atendimento 
          Horário: 24h

**Comment by Dovyski** [comment]
Fixed by https://github.com/grintex/app-covid/pull/160.
