### ISSUE TITLE
"SOBRE A COVID-19": inserção de informações

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#158]
No ícone "SOBRE A COVID-19" inserir no "O que é a COVID-19?" informações, ficando o texto da seguinte maneira:

"A COVID-19 é uma doença causada pelo coronavírus SARS-CoV-2, que apresenta um quadro clínico que varia de infecções assintomáticas a quadros respiratórios graves, como a Síndrome do Desconforto Respiratório Agudo Grave (SDRA)."

**Comment by Dovyski** [comment]
Fixed by https://github.com/grintex/app-covid/pull/160.
