### ISSUE TITLE
[Seção 3] Desenvolver página de sintomas

### ISSUE THREAD

**Issue by JeanCHilger** [grintex/app-covid#19]
**Escopo**: Sintomas

# Descrição
Desenvolver seção sintomas, mostrando um sintoma por tela utilizando o [swiper](https://framework7.io/docs/swiper.html) para navegar entre cada um. Cada tela deve exibir o ícone (de acordo com assets) e um texto descritivo informando a porcentagem de incidência. 

# *Mockup*
Seguir o modelo do *layout* da tela inicial:

![image](https://user-images.githubusercontent.com/19687197/80512013-4c15a800-8953-11ea-87d0-5e60504fcc09.png)

# Assets
## Ícones
- [Febre](https://www.flaticon.com/free-icon/health-check_2790687?term=thermometer%20fever&page=2&position=12)
- [Tosse](https://www.flaticon.com/free-icon/cough_2328345?term=cough&page=1&position=7)
- [Falta de Ar](https://www.flaticon.com/free-icon/bad-breath_2854992?term=bad%20breath&page=1&position=38)
- [Fadiga](https://www.flaticon.com/free-icon/fatigue_2746456?term=fatigue&page=1&position=5)
- [Dores no Corpo](https://www.flaticon.com/free-icon/chest-pain_2167020?term=body%20ache&page=1&position=2)
- [Dores de Cabeça](https://www.flaticon.com/free-icon/headache_1497115?term=headache&page=1&position=3)
- [Diarreia](https://www.flaticon.com/free-icon/diarrhea_2615185?term=diarrhea&page=1&position=9)
- [Dor de Garganta](https://www.flaticon.com/free-icon/sore-throat_2746648)
- [Perda do olfato ou paladar](https://www.flaticon.com/free-icon/taste_2372481?term=taste&page=1&position=30)
- [Náusea ou Vômito](https://www.flaticon.com/free-icon/scared_2367116?term=vomit&page=1&position=10)
- [Nariz escorrendo ou entupido](https://www.flaticon.com/free-icon/runny-nose_2746651)

**Comment by mateusKoppe** [comment]
Feito!
