### ISSUE TITLE
[Seção 5] Implementar página medidas de prevenção

### ISSUE THREAD

**Issue by JeanCHilger** [grintex/app-covid#20]
**Escopo**: Medidas de Prevenção

# Descrição
Desenvolver seção para medidas de prevenção, sendo uma medida por página e utilizando um [swiper](https://framework7.io/docs/swiper.html) para navegar entre elas. Cada tela deve conter ícone (ou vídeo quando for o caso) com um texto descritivo, sendo todas referências do Ministério da Saúde. O conteúdo de cada tela é listado abaixo.

## Medidas
1. Lave com frequência as mãos até a altura dos punhos ou então higienize com álcool em gel 70%. **Incorporar [este vídeo](https://www.youtube.com/watch?time_continue=44&v=krSDE0_KBMs&feature=emb_title)**.
1. Pratique a etiqueta respiratória! Ao tossir ou espirrar, cubra nariz e boca com lenço ou com o braço, e não com as mãos. **Incorporar [este vídeo](https://youtu.be/aEZY2n5wkks?list=PLGGHoUAM3Mh7bSnGFQL8JdcKJtGLSJ28D)**.
1. Evite tocar olhos, nariz e boca com as mãos não lavadas ou higienizadas com álcool em gel 70%.
1. Mantenha uma distância mínima de cerca de 2 metros das outras pessoas.
1. Evite o contato físico como abraços, beijos e apertos de mãos.
1. Utilize máscaras caseiras ou artesanais feitas de tecido em situações de saída de sua residência.
1. Higienize o celular com frequência.
1. Não compartilhe objetos de uso pessoal, como talheres, toalhas, pratos e copos.
1. Evite circulação desnecessária, se puder, fique em casa!
1. Se estiver doente, evite contato físico com outras pessoas, principalmente idosos e doentes crônicos, e fique em casa até melhorar.
1. Durma bem e tenha uma alimentação saudável.
1. Orientação da limpeza de superfícies com álcool 70% e quanto tempo o vírus dura em cada tipo de superfície.
1. Como fazer sua máscara.

# *Mockup*
Seguir o modelo do layout da tela inicial:

![](https://user-images.githubusercontent.com/19687197/80512013-4c15a800-8953-11ea-87d0-5e60504fcc09.png)

# *Assets*
## Ícones
- [medida_3](https://www.flaticon.com/free-icon/avoid_2785821?term=COVID&page=3&position=54)
- [medida_4](https://www.flaticon.com/free-icon/keep-distance_2785828?term=COVID&page=1&position=57)
- [medida_5](https://www.flaticon.com/free-icon/hand-shake_2833570)
- [medida_6](https://www.flaticon.com/free-icon/infected_2750818)
- medida_7: Sem ícone.
- [medida_8](https://www.flaticon.com/free-icon/no-food_631707?term=no%20cutlery&page=1&position=2)
- [medida_9](https://www.flaticon.com/free-icon/ventilate_2833618?term=ventilation&page=1&position=6)
- medida_10: Sem ícone
- medida_11: Sem ícone
- medida_12: Sem ícone
- medida_13: Sem ícone

**Comment by arufonsekun** [comment]
trabalharei nessa issue
