### ISSUE TITLE
[Geral] Atualizar barra de rodapé

### ISSUE THREAD

**Issue by Dovyski** [grintex/app-covid#45]
Alterar a barra de rodapé do app para mostrar o logo da UFFS sem nenhum botão. Acho que não vale a pena confundirmos o usuário com botões no footer.

**Comment by JeanCHilger** [comment]
Vou trabalhar nesta issue

**Comment by mateusKoppe** [comment]
Eu removi o rodape na issue #46 :l

**Comment by JeanCHilger** [comment]
posso fechar a issue então?

**Comment by JeanCHilger** [comment]
> Eu removi o rodape na issue #46 :l

Issue fechada pois não será mais utiilzado rodapé.
