### ISSUE TITLE
[Seção 2] Implementar tela "O que é a COVID-19"

### ISSUE THREAD

**Issue by arufonsekun** [grintex/app-covid#5]
**Escopo**: Sobre a COVID-19
## Descrição

- O que é a COVID-19?
- O layout da tela deve ser em forma de [fashcard](https://framework7.io/docs/cards.html#card-layout);
- A transição entre os cards deve ser feito através do [swipe slider](https://framework7.io/docs/swiper.html);

## ***Mockup***
Seguir o modelo do layout da tela inicial:

![](https://user-images.githubusercontent.com/19687197/80512013-4c15a800-8953-11ea-87d0-5e60504fcc09.png)

## Assets
 - [cough_icon](https://www.flaticon.com/free-icon/cough_2790668)

**Comment by arufonsekun** [comment]
Estou trabalhando nessa issue

**Comment by Dovyski** [comment]
Beleza! Eu crio já todas as páginas do app ou apenas os links agora?

**Comment by arufonsekun** [comment]
se quiser criar as páginas eu espero até tu mandar o PR

**Comment by Dovyski** [comment]
Estou moendo. Já mando o PR.

**Comment by arufonsekun** [comment]
enquanto isso vou criando as outras issues

**Comment by Dovyski** [comment]
Merged em 599a4527273c96dbc17e2694b7a1a93fc9ab6789. Pode trabalhar no arquivo `pages/about-covid.f7.html`.

**Comment by arufonsekun** [comment]
nice
