### ISSUE TITLE
Ícones não carregados na página "Onde procurar ajuda"

### ISSUE THREAD

**Issue by Dovyski** [grintex/app-covid#68]
Os ícones da página "Onde procurar ajuda" não estão carregando. Acho que eles não foram comitados.

<img width="329" alt="bug-where-help" src="https://user-images.githubusercontent.com/512405/80894475-a2ffe200-8cb1-11ea-80ba-beb295bdab4c.png">

Testei nesse build: https://ci.uffs.cc/app-covid/dev/4469b11fe9b0300c85e45566e64e38ef63296e9e/

Acho que o @JeanCHilger deve ter os ícones.

**Comment by JeanCHilger** [comment]
Irei verificar isto.

**Comment by JeanCHilger** [comment]
Os ícones foram commitados, deveria estar funcionando.

**Comment by JeanCHilger** [comment]
Irei corrigir este bug, o problema é que tem uma barra no início do caminho da imagem: `/static/images/...`
