### ISSUE TITLE
Rodapé e cabeçalho ainda estão no padrão antigo

### ISSUE THREAD

**Issue by Dovyski** [grintex/app-covid#72]
Olhando a issue #46 e o PR https://github.com/grintex/app-covid/pull/64, parece que o cabeçalho e o rodapé foram arrumados para o que combinamos. Estou testando o app, porém, e o cabeçalho e o rodapé continuam lá.

Eu acho que o commit https://github.com/grintex/app-covid/commit/455045a0e3976759e080bc4d0527394707bb2484 reverteu as mudanças do PR.

**Comment by arufonsekun** [comment]
eu acho que não foi feito o merge da pr #64

**Comment by Dovyski** [comment]
Re-aari o PR e efetuei o merge em https://github.com/grintex/app-covid/commit/dc99a2a09eb89b2a1f1be8c3692192047756a115.
