### ISSUE TITLE
Alteração do texto da conduta se tem sintomas que NÃO se encaixam como síndrome gripal OU com síndrome gripal SEM condições de risco

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#83]
Alterar texto da conduta se assinalar sintomas que NÃO se encaixam como síndrome gripal ou falta de ar OU se assinalar síndrome gripal + “não me encaixo nessas condições” =

 “Com base em suas respostas, a orientação é que você mantenha as condutas de precaução e prevenção, mantendo-se em isolamento social. Recomendamos que monitore seus sintomas e em caso de persistência ou piora entre em contato com a central de teleatendimento de Chapecó pelo número (49) 2049-6500 ou procure atendimento médico presencial. Em caso de dúvidas sobre COVID-19 ligue para a central de teleatendimento de dúvidas gerais de Chapecó pelo número (49) 3321.0027”.

**Comment by JeanCHilger** [comment]
Issue resolvida no PR anterior
