### ISSUE TITLE
Bug No teste "Estou com covid-19"

### ISSUE THREAD

**Issue by rafaelfagu** [grintex/app-covid#90]
Na opção Estou com COVID-19?"
Independente da seleção da opções "adulto" ou "criança" na proxima opção
"Quais sintomas está sentindo?" se o usuário não marcar nada e clicar em "continuar", o app mostra a mensagem de erro "Not found - Sorry - Requested content not found".
A sugestão é que se o usuário não marcar nada, seja igual quando marcar a opção "nenhum sintoma".

**Comment by JeanCHilger** [comment]
issue resolvida em PRs anteriores, porém não marquei esta issue :cry:.
