### ISSUE TITLE
"ESTOU COM COVID-19?" : alteração do texto e critério da CRIANÇA COM SÍNDROME GRIPAL 

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#93]
No ícone "ESTOU COM COVID-19?" alterar texto da tela de resposta da CRIANÇA COM SÍNDROME GRIPAL para:

“Com base em suas respostas, a orientação é que você entre em contato com o teleatendimento de Chapecó pelo número (49) 2049-6500”.

Além disso, conforme orientado pela prof. Thaís, para aparecer essa resposta ampliar o critério para:
- Febre OU perda do olfato ou paladar (recente ou piorando) + PELO MENOS um dos seguintes: dor de garganta OU tosse OU nariz entupido ou escorrendo.

**Comment by JeanCHilger** [comment]
@brendathomas, a resolução foi implementada, peço por gentileza para que sejam realizados novos testes para verificar se o comportamento está como desejado (não tenho certeza se pude implementar bem a ideia :disappointed:)

**Comment by brendathomas** [comment]
@JeanCHilger Deu super certo! :)
