### ISSUE TITLE
"SOBRE A COVID-19": possibilidade de mudar para formato de flashcards e justificar texto

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#95]
Ver possibilidade de mudar o item "SOBRE A COVID-19" para formato de flashcards, colocando uma seta indicando que deve passar para o lado para ver cada tópico. 

Justificar textos do ícone.

**Comment by arufonsekun** [comment]
@brendathomas, nós da equipe de desenvolvimento discutimos sobre esse modo de organizar as informações e o implementamos (como pode ser visto [aqui](https://ci.uffs.cc/app-covid/dev/21549390be066dada3577ad185b063ea0f064d2c/)), porém optamos pelo layout no formato de lista como encontra-se [atualmente](https://ci.uffs.cc/app-covid/dev/cbb771bd5e3f126263acb1f5647f3c1d57aa4270/), pois o espaço da tela é melhor utilizado e o usuário fará o uso do _scroll_ para navegar entre as informações, dinâmica que de certo modo ele está mais habituado, um exemplo são apps como o Facebook, Twitter e Instagram. Peço desculpas por não envolver vocês @brendathomas e @rafaelfagu nessa discussão desde o início, estamos sempre abertos a opiniões e sugestões.

**Comment by brendathomas** [comment]
Vcs tem razão!! Ficou melhor assim mesmo :) sempre bom diferentes opiniões

**Comment by rafaelfagu** [comment]
Por mim está ok também! Só mencionamos pois pensamos que vocês não tinham visto no documento e não que seria uma alteração para melhor aproveitamento da tela. 👍🏽

**Comment by arufonsekun** [comment]
Entendi, de certa forma quando eu mandei a nova alteração eu deveria ter comentado sobre a nossa decisão, uma lacuna na comunicação de minha parte. 
Obrigado pelo _feedback_ :blush:, como todos estão de acordo acho que podemos fechar a _issue_.
