### ISSUE TITLE
"SOBRE A COVID-19": alteração de imagem do tópico "COMO É TRANSMITIDO?"

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#96]
Alteração de imagem do tópico "Como é transmitido" no "SOBRE A COVID-19?" para a imagem a seguir
 
https://www.flaticon.com/free-icon/handshake_2834096?term=transmission&page=1&position=15

**Comment by JeanCHilger** [comment]
@brendathomas, o ícone ficará igual ao ícone em "1. Aperto de mão" na mesma seção, isto está correto?

**Comment by brendathomas** [comment]
@JeanCHilger Até estava, mas depois que falou achei melhor mudar a imagem mesmo. Vamos colocar essa então:

https://www.flaticon.com/free-icon/virus-transmission_2904372?term=COVID%20transmission&page=1&position=14
