### ISSUE TITLE
 "SOBRE A COVID-19": alteração de imagem no subtópico "OBJETOS OU SUPERFÍCIES CONTAMINADAS" 

### ISSUE THREAD

**Issue by brendathomas** [grintex/app-covid#97]
Alteração de imagem no subtópico "Objetos ou superfícies contaminadas" no ícone "SOBRE A COVID-19" para a imagem a seguir

https://www.flaticon.com/free-icon/doorknob_2746421

**Comment by arufonsekun** [comment]
trabalharei nessa issue
