### ISSUE TITLE
Correção no cabeçalho No subtópico "Quais sintomas está sentindo?"

### ISSUE THREAD

**Issue by rafaelfagu** [grintex/app-covid#99]
No menu "Estou com COVID-19?" 
Nas opções "Adulto" e "Criança"
No subtópico "Quais sintomas está sentindo?" a mensagem no cabeçalho "Faça uma autoavaliação do seu estado de saúde" deve ser substituída pela palavra "Sintomas".

**Comment by Dovyski** [comment]
@JeanCHilger liberei essa tarefa para focar na do Google Analytics. Desculpe ter trancado ela.

**Comment by Dovyski** [comment]
Implementada no PR do google analytics.
